#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t debugfs none /sys/kernel/debug

cat <<!


Boot took $(cut -d' ' -f1 /proc/uptime) seconds

___________            .__            
\__    ___/__.__. ____ |  |__   ____  
  |    | <   |  |/ ___\|  |  \_/ __ \ 
  |    |  \___  \  \___|   Y  \  ___/ 
  |____|  / ____|\___  >___|  /\___  >
          \/         \/     \/     \/ 


Welcome to Tyche


!

# Open a shell if switch root fail
error() {
	echo "Failed to switch root to Ubuntu"
    exec /bin/sh
}

error_part5() {
  echo "Failed to mount on sdb2, try sdb5"
  mknod /dev/sdb5 b 8 21
  mount /dev/sdb5 /newroot || error
  exec switch_root /newroot /sbin/init || error
}

# Install disk
# We have a disk B with 2 partitions for now
mknod /dev/sdb  b 8 16
mknod /dev/sdb1 b 8 17
mknod /dev/sdb2 b 8 18
#
## Create new root
mkdir /newroot
mount /dev/sdb2 /newroot || error_part5
#
## Switch root
exec switch_root /newroot /sbin/init || error

exec /bin/sh
