#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t debugfs none /sys/kernel/debug

cat <<!


Boot took $(cut -d' ' -f1 /proc/uptime) seconds

___________            .__            
\__    ___/__.__. ____ |  |__   ____  
  |    | <   |  |/ ___\|  |  \_/ __ \ 
  |    |  \___  \  \___|   Y  \  ___/ 
  |____|  / ____|\___  >___|  /\___  >
          \/         \/     \/     \/ 


Welcome to Tyche


!
exec /bin/sh
